python .\make_migration_timelines.py --init_day 18 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 19 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 20 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 21 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 22 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 23 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 24 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 25 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 26 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 27 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 28 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 29 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 30 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 31 --init_month 10 --start_year 2020
python .\make_migration_timelines.py --init_day 01 --init_month 11 --start_year 2020
python .\make_migration_timelines.py --init_day 02 --init_month 11 --start_year 2020
python .\make_migration_timelines.py --init_day 03 --init_month 11 --start_year 2020
python .\make_migration_timelines.py --init_day 04 --init_month 11 --start_year 2020
python .\make_migration_timelines.py --init_day 05 --init_month 11 --start_year 2020
python .\make_migration_timelines.py --init_day 06 --init_month 11 --start_year 2020
